'use client';

import type { Metadata } from 'next';
import React from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MessageCircle, Activity, User } from 'lucide-react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="w-full max-w-md mx-auto">
          {/* フィード画面 */}
          <div className="bg-white h-screen flex flex-col">
            {/* ヘッダー */}
            <div className="bg-blue-500 text-white p-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <span className="text-sm">現在のチャレンジ</span>
                  <button className="bg-blue-600 px-3 py-1 rounded-full text-sm flex items-center">
                    東京マラソン2025 ▼
                  </button>
                </div>
              </div>
              <div className="mt-2 flex justify-between text-sm">
                <span>残り: 82日</span>
                <span>累計: 124.5km</span>
              </div>
            </div>

            {/* タイムライン */}
            <div className="flex-1 overflow-auto p-4 space-y-4">
              {/* アクティビティカード */}
              <div className="bg-white border rounded-lg p-4">
                <div className="flex items-start space-x-3">
                  <div className="w-10 h-10 bg-gray-200 rounded-full" />
                  <div className="flex-1">
                    <div className="font-medium">山田太郎</div>
                    <div className="text-sm text-gray-500">10km走りました</div>
                    <div className="mt-2 text-sm">
                      今日は調子が良かったです！
                    </div>
                  </div>
                </div>
              </div>
              {/* メッセージカード */}
              <div className="bg-white border rounded-lg p-4">
                <div className="flex items-start space-x-3">
                  <div className="w-10 h-10 bg-gray-200 rounded-full" />
                  <div className="flex-1">
                    <div className="font-medium">鈴木花子</div>
                    <div className="mt-1 text-sm">
                      みんな頑張ってますね！私も明日から再開します💪
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {children}

            {/* フローティングアクションボタン */}
            <button className="fixed right-4 bottom-20 bg-blue-500 text-white p-4 rounded-full shadow-lg">
              <MessageCircle size={24} />
            </button>

            {/* ボトムナビゲーション */}
            <div className="bg-white border-t flex justify-around py-2">
              <button className="p-2 text-blue-500 flex flex-col items-center">
                <MessageCircle size={24} />
                <span className="text-xs">フィード</span>
              </button>
              <button className="p-2 text-gray-500 flex flex-col items-center">
                <Activity size={24} />
                <span className="text-xs">記録</span>
              </button>
              <button className="p-2 text-gray-500 flex flex-col items-center">
                <User size={24} />
                <span className="text-xs">プロフィール</span>
              </button>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
