openapi: "3.0.2"
info:
  title: "Runmie API"
  version: "1.0"
servers:
  - url: "http://localhost:8000"
    description: "Local server"
paths:
  /signup:
    post:
        summary: "Create a new user"
  /me:
    get:
        summary: "Get current user"
        responses:
            200:
                description: "User found"
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/User"

components:
    schemas:
        User:
          type: "object"
          properties:
              id:
                type: "string"
              name:
                type: "string"
          required:
            - id
            - name
