openapi: "3.0.2"
info:
  title: "Runmie API"
  version: "1.0"
servers:
  - url: "http://localhost:8000"
    description: "Local server"
paths:
  /signup:
    post:
        operationId: post-signup
        summary: "Create a new user"
        responses:
            201:
                description: "User created"
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Success"
  /me:
    get:
        operationId: get-me
        summary: "Get current user"
        responses:
            200:
                description: "User found"
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/User"
    patch:
        operationId: patch-me
        summary: "Update current user"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                required:
                    - name
        responses:
          201:
            description: "User updated"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Success"
  /challenges:
    get:
        operationId: get-challenges
        summary: "Get all challenges"
        responses:
            200:
                description: "Challenges found"
                content:
                    application/json:
                        schema:
                            type: "array"
                            items:
                                $ref: "#/components/schemas/Challenge"
    post:
        operationId: post-challenges
        summary: "Create a new challenge"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  description:
                    type: string
                    nullable: true
                  targetDate:
                    type: string
                    format: date
                    description: "Challenge target date in YYYY-MM-DD format"
                  status:
                    type: string
                    enum:
                      - "draft"
                      - "active"
                required:
                    - title
                    - description
                    - targetDate
                    - status
        responses:
            201:
                description: "Challenge created"
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Success"
  /challenge_members:
      post:
        operationId: post-challenge-members
        summary: "Join a challenge"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  inviteCode:
                    type: string
                required:
                    - inviteCode
        responses:
            201:
                description: "Challenge joined"
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Success"
  /challenge_members/invite_code:
      post:
        operationId: post-challenge-members-invite-code
        summary: "Create an invite code for a challenge"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  challengeId:
                    type: string
                required:
                    - challengeId
        responses:
            201:
                description: "Invite code created"
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                              code:
                                type: string
                            required:
                                - code
      get:
        operationId: get-challenge-members-invite-code
        summary: "Get invite code for a challenge"
        parameters:
          - name: challengeId
            in: query
            required: true
            schema:
              type: string
            description: "Challenge ID to get invite code for"
        responses:
            200:
                description: "Invite code retrieved"
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                              code:
                                type: string
                              isValid:
                                type: boolean
                            required:
                                - code
                                - isValid

components:
    schemas:
        User:
          type: "object"
          properties:
              id:
                type: "string"
              name:
                type: "string"
          required:
            - id
            - name
        Challenge:
            type: "object"
            properties:
                id:
                  type: "string"
                title:
                  type: "string"
                description:
                  type: "string"
                  nullable: true
                targetDate:
                  type: "string"
                  format: "date"
                status:
                  type: "string"
                  enum:
                    - "draft"
                    - "active"
                    - "completed"
            required:
                - id
                - name
                - description
                - targetDate
                - status
        Success:
          type: "object"
          properties:
            success:
              type: "boolean"
          required:
            - success
