/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/signup': {
    parameters: {};
    /** Create a new user */
    post: {
      parameters: {};
    };
  };
  '/me': {
    parameters: {};
    /** Get current user */
    get: {
      parameters: {};
      responses: {
        /** @description User found */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['User'];
          };
        };
      };
    };
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    User: {
      id: string;
      name: string;
    };
  };
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
